// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");

var server = Http.createServer((function (_, res) {
        res.write("Hello world", undefined);
        res.end();
        return /* () */0;
      }));

server.listen(60023);

server.on("listening", (function () {
        console.log("listening on port 60023");
        return /* () */0;
      }));

exports.server = server;
/* server Not a pure module */
